### ISSUE TITLE
ERROR: for app  Container "f3c97443ff32" is unhealthy.

### ISSUE THREAD

**Issue by prakhargurunani** [Samwalton9/hashtags#26]
I am unable to start the container. I am using windows container in docker settings and experiments: True.
![Screenshot (51)](https://user-images.githubusercontent.com/43035576/55155566-b8850d00-517d-11e9-8bb2-48e3b2b40951.png)

**Comment by prakhargurunani** [comment]
```
healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-phashtag"]
     timeout: 20s
     retries: 10
```

Its showing ```unhealthy```. Do I have to change something here 👆
